name: Pull Request Checks
run-name: ${{ github.actor }} is checking if all PR criteria is met
on:
  pull_request:
    branches:
      - main
jobs:
  pre-commit-check:
    name: Checking if pre-commit is verified
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Fetching docker to test if pre-commit has run
        uses: addnab/docker-run-action@v3
        with:
          image: swateekj/verify-pre-commit:latest
          options: -v ${{ github.workspace }}:/app
          run: |
            git config --global --add safe.directory /app
            cd /app
            echo $0
            set -x
            status=0
            pre-commit run --all-files || status=$?
            # git config --global --add safe.directory /app
            if [[ $status -ne 0 ]]; then
              exit 1 # fail the job
            fi
      - run: echo "üçè This job's status is ${{ job.status }}."
