name: Pull Request Checks
run-name: ${{ github.actor }} is testing if PreCommits have run
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
jobs:
  Precommit-Checks:
    runs-on: swateekj/verify-pre-commit:latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Running pre-commit check script
        run: |
          set -x
          status=0
          pre-commit run --all-files || status=$?
          if [[ $status -ne 0 ]]; then
            # cat /root/.cache/pre-commit/pre-commit.log
            exit 1 # fail the job
          fi
      - run: echo "ğŸ This job's status is ${{ job.status }}."
